[build]
  publish = "dist"
  command = "npm run build"

# Configurações de proxy para a API principal
[[redirects]]
  from = "/api-proxy/*"
  to = "https://anime-api-netf.onrender.com/api/:splat"
  status = 200
  force = true

# Proxy para animefire removido - retornava HTML em vez de JSON
# O sistema agora usa dados mock quando APIs externas falham

# Proxy para vídeos do Blogger
[[redirects]]
  from = "/api/blogger/*"
  to = "https://blogger.googleusercontent.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Proxy para vídeos do lightspeedst.net
[[redirects]]
  from = "/api/video/*"
  to = "https://lightspeedst.net/:splat"
  status = 200
  force = true

# Proxy genérico para outros domínios de vídeo
[[redirects]]
  from = "/api/video-generic/*"
  to = "https://:splat"
  status = 200
  force = true

# Proxy para CDNs de vídeo comuns
[[redirects]]
  from = "/api/cdn/*"
  to = "https://:splat"
  status = 200
  force = true

# Fallback para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança e performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; media-src 'self' https: blob:; connect-src 'self' https: wss:; font-src 'self' https:; frame-src 'self' https: blob: data:; object-src 'none'; base-uri 'self'; form-action 'self';"
    X-From = "Netlify"
    Cache-Control = "public, max-age=300"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Range, User-Agent, Referer, Accept"
    Access-Control-Expose-Headers = "Content-Length, Content-Range, Accept-Ranges"

# Headers específicos para arquivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Headers para arquivos de API JSON
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Content-Type = "application/json; charset=utf-8"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Headers para vídeos
[[headers]]
  for = "*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Accept-Ranges = "bytes"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Range, Content-Type"
    Access-Control-Expose-Headers = "Content-Length, Content-Range, Accept-Ranges"

# Headers para imagens
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

# Headers para fontes
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Configurações de timeout e performance
[functions]
  node_bundler = "esbuild"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
