[build]
  publish = "dist"
  command = "npm run build"

# Configurações de proxy para a API
[[redirects]]
  from = "/api-proxy/*"
  to = "https://anime-api-netf.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Fallback para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
