[build]
  publish = "dist"
  command = "npm run build"

# Configurações de proxy para a API
[[redirects]]
  from = "/api-proxy/*"
  to = "https://anime-api-netf.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Proxy para APIs externas (animefire.plus)
[[redirects]]
  from = "/api/external/*"
  to = "https://animefire.plus/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Proxy para vídeos do lightspeedst.net
[[redirects]]
  from = "/api/video/*"
  to = "https://lightspeedst.net/:splat"
  status = 200
  force = true
  headers = {
    X-From = "Netlify",
    User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    Referer = "https://animefire.plus/"
  }

# Fallback para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
